<?php
namespace App\Tests\Infrastructure\Command;

use App\Infrastructure\Command\WhichOneWinsLawsuitCommand;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;

class WhichOneWinsLawsuitCommandStub extends WhichOneWinsLawsuitCommand
{
    public function configure(): void
    {
        parent::configure();
    }

    public function execute(InputInterface $input, OutputInterface $output): int
    {
        return parent::execute($input, $output); // TODO: Change the autogenerated stub
    }
}
