#index:
#    path: /
#    controller: App\Controller\DefaultController::index
which_one_wins:
     path: /which-one-wins/{plaintiff}/vs/{defendant}
     controller: App\Infrastructure\Controller\WhichOneWinsController